### ISSUE TITLE
Ventus as window manager

### ISSUE THREAD

**Issue by lawrencenull** [kurisubrooks/glass#3]
Have you considered using Ventus as the window manager. It has the majority of the proposed wm features built in.

https://github.com/rlamana/Ventus

**Comment by kurisubrooks** [comment]
Just took a look at this, i've known about this for a while, but I really don't like the animations, how slow they are. Plus it seems it has the same amount of bugs as my current system that uses jQuery UI, so I think i'll leave this for now.

**Comment by kurisubrooks** [comment]
Also, it's worth mentioning that this project only started out as a Design project of mine. I thought it'd be good experience for me to design an operating system-type desktop environment. This project's a bit out of date too, and I don't see a real purpose in upkeep.

If others are however interested in the project or would like to see it still in development, i'm more than willing to take a look at suggestions.

**Comment by lawrencenull** [comment]
Yes I hate the animations in Ventus as well, but they are CSS based and can be removed. I like the way your system builds the apps. I think I will try to turn it into a chrome os type of look and feel. Probably use it as a basic splashtop for my girlfriend. I'm gonna try to get files to work as a chrome app within the os... It'll be interesting to try.

![os](https://cloud.githubusercontent.com/assets/1301229/17562831/94b25220-5efa-11e6-8be2-af86931a3a0c.png)
![login](https://cloud.githubusercontent.com/assets/1301229/17562836/a027d0e4-5efa-11e6-8b7e-301a6f7f40e8.jpg)

**Comment by kurisubrooks** [comment]
If you're interested, i've made already made a [semi-working File explorer](https://github.com/kurisubrooks/files) with Electron.
If you converted Glass to an Electron app, you could easily integrate the code into a wrapped app.

**Comment by kurisubrooks** [comment]
Another benefit of making this use Electron would be proper OS integration, aswell as `<webview>` (like an iframe, but doesn't block content with the X-Frame header, and essentially a threaded browser window)

**Comment by kurisubrooks** [comment]
If this ran purely on Electron and Node, maybe you could find a way to integrate further, into the desktop environment even, hide the taskbar and replace it with our own, make system calls from within the app itself, behaving as an OS. 

Probably entirely possible with Linux with some C bindings. (Unfortunately I have no knowledge of C however.)

**Comment by lawrencenull** [comment]
Yes I saw that, I was thinking of putting this on an embedded system, and chromium still has the best support for embedded on linux. I have a Pine64 board laying around. Was going to use play around a bit and see what I can make. I do wish you had finished the min, max buttons though, less work for me ;)

**Comment by kurisubrooks** [comment]
Haha, sorry. It shouldn't be too hard with jQuery UI. If you want to move it to Ventus for better window managing, feel free. I might be able to offer some help if I can find time, but i'm quite busy with work and whatnot currently. I'd love to see what you make of Glass, keep me updated!

**Comment by lawrencenull** [comment]
I will, thanks for creating the project.

**Comment by kurisubrooks** [comment]
Hey, just started working on a remaster of this project under Electron with node.js, hoping to make it  into a semi-functioning os.

Was just wondering if you ever finished or made significant progress on your on personal fork?

Currently looking into using Ventus as the window manager for this rewrite aswell, so that may be something that interests you. Ventus unfortunately isn't compatible with node.js as of right now, but the owner's looking into it.
